apiVersion: apps/v1
kind: Deployment
metadata:
  name: spignos-backend
  labels:
    app: spignos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spignos
  template:
    metadata:
      labels:
        app: spignos
    spec:
      containers:
      - name: backend
        image: debian:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spignos-service
spec:
  selector:
    app: spignos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spignos-ingress
spec:
  rules:
  - host: spignos.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spignos-service
            port:
              number: 80
