# pyproject.toml

[tool.black]
line-length = 100
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | venv
  | __pycache__
  | llm_models
  | migrations
  | node_modules
)/
'''
