apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: spignos-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              value: "spignos"
            - name: POSTGRES_USER
              value: "spignos"
            - name: POSTGRES_PASSWORD
              value: "spignos_secret"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
