# Generated by Django 5.2.4 on 2025-07-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="text",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response",
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("USER", "User"), ("AI", "AI")], default="USER", max_length=4
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
